export interface SatelliteConfig {
  id: string;
  name: string;
  noradId?: string;
  category: 'spaceStations' | 'brightest' | 'weather' | 'gps' | 'earthObs' | 'starlink' | 'military' | 'other';
  altitudeM: number;
  inclinationRad: number;
  omega0: number;
  argLat0: number;
  color: string;
  description: string;
}

export const SATELLITES: SatelliteConfig[] = [
  // 1. SPACE STATIONS (#00FFF7)
  {
    id: 'iss',
    name: 'ISS (SPACE STATION)',
    noradId: '25544',
    category: 'spaceStations',
    altitudeM: 420_000,
    inclinationRad: (51.64 * Math.PI) / 180,
    omega0: 0.0,
    argLat0: 0.0,
    color: '#00FFF7',
    description: 'International Space Station. Joint collaboration habitable artificial satellite in low Earth orbit.',
  },
  {
    id: 'tiangong',
    name: 'TIANGONG SPACE STATION',
    noradId: '48274',
    category: 'spaceStations',
    altitudeM: 390_000,
    inclinationRad: (41.58 * Math.PI) / 180,
    omega0: 2.8,
    argLat0: 1.8,
    color: '#00FFF7',
    description: 'Chinese Space Station. Multi-module space station operating in low Earth orbit.',
  },

  // 2. BRIGHTEST SATELLITES (#F0ABFC)
  {
    id: 'hubble',
    name: 'HUBBLE SPACE TELESCOPE',
    noradId: '20580',
    category: 'brightest',
    altitudeM: 540_000,
    inclinationRad: (28.47 * Math.PI) / 180,
    omega0: 1.2,
    argLat0: 0.5,
    color: '#F0ABFC',
    description: 'HST Observatory. Imaged deep cosmic structures from orbit since 1990.',
  },
  {
    id: 'envisat',
    name: 'ENVISAT MONITOR',
    noradId: '27386',
    category: 'brightest',
    altitudeM: 790_000,
    inclinationRad: (98.54 * Math.PI) / 180,
    omega0: -0.8,
    argLat0: 3.2,
    color: '#F0ABFC',
    description: 'Large inactive Earth observation satellite. Launched by ESA in 2002.',
  },
  {
    id: 'genesis-1',
    name: 'GENESIS I EXPANDABLE',
    noradId: '29252',
    category: 'brightest',
    altitudeM: 560_000,
    inclinationRad: (64.5 * Math.PI) / 180,
    omega0: 0.5,
    argLat0: 2.1,
    color: '#F0ABFC',
    description: 'Experimental inflatable space habitat prototype launched by Bigelow Aerospace.',
  },
  {
    id: 'genesis-2',
    name: 'GENESIS II EXPANDABLE',
    noradId: '31789',
    category: 'brightest',
    altitudeM: 560_000,
    inclinationRad: (64.5 * Math.PI) / 180,
    omega0: 1.7,
    argLat0: 4.3,
    color: '#F0ABFC',
    description: 'Second experimental inflatable habitat prototype launched in 2007.',
  },

  // 3. WEATHER (#A78BFA)
  {
    id: 'noaa-19',
    name: 'NOAA-19 CLIMATE',
    noradId: '33591',
    category: 'weather',
    altitudeM: 870_000,
    inclinationRad: (99.0 * Math.PI) / 180,
    omega0: 2.1,
    argLat0: 1.0,
    color: '#A78BFA',
    description: 'National Oceanic and Atmospheric Administration weather satellite in polar orbit.',
  },
  {
    id: 'noaa-20',
    name: 'NOAA-20 WEATHER',
    noradId: '43010',
    category: 'weather',
    altitudeM: 824_000,
    inclinationRad: (98.7 * Math.PI) / 180,
    omega0: 0.3,
    argLat0: 5.2,
    color: '#A78BFA',
    description: 'JPSS weather forecasting satellite providing high-resolution global atmospheric profiles.',
  },
  {
    id: 'goes-16',
    name: 'GOES-16 WEATHER (GEO)',
    noradId: '41866',
    category: 'weather',
    altitudeM: 35_786_000,
    inclinationRad: (0.1 * Math.PI) / 180,
    omega0: 3.5,
    argLat0: 0.2,
    color: '#A78BFA',
    description: 'Geostationary environmental satellite monitoring weather across East Americas from the GEO belt.',
  },
  {
    id: 'meteosat-11',
    name: 'METEOSAT-11 WEATHER',
    noradId: '42830',
    category: 'weather',
    altitudeM: 35_786_000,
    inclinationRad: (0.8 * Math.PI) / 180,
    omega0: -2.3,
    argLat0: 2.9,
    color: '#A78BFA',
    description: 'European meteorological geostationary weather satellite providing coverage over Europe/Africa from the GEO belt.',
  },

  // 4. GPS (#22C55E)
  {
    id: 'gps-prn01',
    name: 'GPS BIIRM-1 (PRN 01)',
    noradId: '28474',
    category: 'gps',
    altitudeM: 20_200_000,
    inclinationRad: (55.0 * Math.PI) / 180,
    omega0: 0.0,
    argLat0: 0.8,
    color: '#22C55E',
    description: 'US GPS block IIR-M navigational satellite serving global military/civilian networks from medium Earth orbit.',
  },
  {
    id: 'gps-prn02',
    name: 'GPS BIIF-1 (PRN 02)',
    noradId: '36585',
    category: 'gps',
    altitudeM: 20_200_000,
    inclinationRad: (55.0 * Math.PI) / 180,
    omega0: (60.0 * Math.PI) / 180,
    argLat0: 2.4,
    color: '#22C55E',
    description: 'US GPS block IIF navigational satellite providing ultra-precise atomic clocks from medium Earth orbit.',
  },
  {
    id: 'glonass-701',
    name: 'GLONASS-701 (RUSSIAN)',
    noradId: '28915',
    category: 'gps',
    altitudeM: 19_100_000,
    inclinationRad: (64.8 * Math.PI) / 180,
    omega0: 1.5,
    argLat0: 4.1,
    color: '#22C55E',
    description: 'Russian global navigation satellite system providing civilian/defense services from medium Earth orbit.',
  },
  {
    id: 'galileo-e01',
    name: 'GALILEO-E01 (EUROPEAN)',
    noradId: '37846',
    category: 'gps',
    altitudeM: 23_222_000,
    inclinationRad: (56.0 * Math.PI) / 180,
    omega0: -1.8,
    argLat0: 1.5,
    color: '#22C55E',
    description: 'European union global navigation system, offering independent precise positioning from medium Earth orbit.',
  },

  // 5. EARTH OBSERVATION (#F97316)
  {
    id: 'terra',
    name: 'TERRA MONITOR (NASA)',
    noradId: '25994',
    category: 'earthObs',
    altitudeM: 705_000,
    inclinationRad: (98.2 * Math.PI) / 180,
    omega0: 0.8,
    argLat0: 0.4,
    color: '#F97316',
    description: 'Flagship NASA Earth scientific research satellite monitoring biosphere dynamics.',
  },
  {
    id: 'aqua',
    name: 'AQUA WATER (NASA)',
    noradId: '27424',
    category: 'earthObs',
    altitudeM: 705_000,
    inclinationRad: (98.2 * Math.PI) / 180,
    omega0: 0.8,
    argLat0: 3.5, 
    color: '#F97316',
    description: 'NASA climate monitoring satellite studying the global water cycle and precipitation.',
  },
  {
    id: 'landsat-8',
    name: 'LANDSAT-8 GEOLOGICAL',
    noradId: '39084',
    category: 'earthObs',
    altitudeM: 705_000,
    inclinationRad: (98.2 * Math.PI) / 180,
    omega0: 3.1,
    argLat0: 1.6,
    color: '#F97316',
    description: 'Joint NASA/USGS earth resource mapping satellite capturing high-detail spectral imagery.',
  },
  {
    id: 'sentinel-2a',
    name: 'SENTINEL-2A (ESA)',
    noradId: '40697',
    category: 'earthObs',
    altitudeM: 786_000,
    inclinationRad: (98.6 * Math.PI) / 180,
    omega0: -0.5,
    argLat0: 2.2,
    color: '#F97316',
    description: 'European Commission Copernicus multispectral imaging land monitoring satellite.',
  },

  // 6. STARLINK (#FFFFFF)
  {
    id: 'starlink-1007',
    name: 'STARLINK-1007 (COMMS)',
    noradId: '44713',
    category: 'starlink',
    altitudeM: 550_000,
    inclinationRad: (53.0 * Math.PI) / 180,
    omega0: 0.1,
    argLat0: 0.9,
    color: '#FFFFFF',
    description: 'SpaceX Starlink broadband communication satellite in low Earth orbit.',
  },
  {
    id: 'starlink-3012',
    name: 'STARLINK-3012 (COMMS)',
    noradId: '49281',
    category: 'starlink',
    altitudeM: 550_000,
    inclinationRad: (53.0 * Math.PI) / 180,
    omega0: 0.8,
    argLat0: 2.7,
    color: '#FFFFFF',
    description: 'SpaceX Starlink internet array component providing global low-latency internet.',
  },
  {
    id: 'starlink-4015',
    name: 'STARLINK-4015 (COMMS)',
    noradId: '53600',
    category: 'starlink',
    altitudeM: 550_000,
    inclinationRad: (53.0 * Math.PI) / 180,
    omega0: 1.5,
    argLat0: 4.8,
    color: '#FFFFFF',
    description: 'SpaceX Starlink constellation nodes forming global space network grids.',
  },
  {
    id: 'starlink-5021',
    name: 'STARLINK-5021 (COMMS)',
    noradId: '55610',
    category: 'starlink',
    altitudeM: 550_000,
    inclinationRad: (53.0 * Math.PI) / 180,
    omega0: 2.2,
    argLat0: 6.1,
    color: '#FFFFFF',
    description: 'Active Starlink broadband nodes serving remote and marine locations.',
  },

  // 7. MILITARY (#3B82F6)
  {
    id: 'usa-243',
    name: 'USA-243 (WGS-5 MILCOM)',
    noradId: '39172',
    category: 'military',
    altitudeM: 35_786_000,
    inclinationRad: (12.0 * Math.PI) / 180,
    omega0: 0.4,
    argLat0: 1.5,
    color: '#3B82F6',
    description: 'Wideband Global SATCOM tactical communications satellite for US Dept of Defense in geostationary orbit.',
  },
  {
    id: 'usa-276',
    name: 'USA-276 RECONNAISSANCE',
    noradId: '42689',
    category: 'military',
    altitudeM: 400_000,
    inclinationRad: (50.0 * Math.PI) / 180,
    omega0: 2.7,
    argLat0: 3.3,
    color: '#3B82F6',
    description: 'Classified National Reconnaissance Office (NRO) intelligence gathering satellite.',
  },
  {
    id: 'usa-290',
    name: 'USA-290 (NROL-71 SPY)',
    noradId: '43906',
    category: 'military',
    altitudeM: 410_000,
    inclinationRad: (74.0 * Math.PI) / 180,
    omega0: -1.2,
    argLat0: 5.6,
    color: '#3B82F6',
    description: 'Classified American electro-optical spy satellite launched in 2019.',
  },
  {
    id: 'kosmos-2542',
    name: 'KOSMOS-2542 (RUSSIAN)',
    noradId: '44797',
    category: 'military',
    altitudeM: 370_000,
    inclinationRad: (97.9 * Math.PI) / 180,
    omega0: 3.1,
    argLat0: 0.1,
    color: '#3B82F6',
    description: 'Russian inspector satellite designed to monitor space targets in LEO.',
  },

  // 8. OTHER (#94A3B8)
  {
    id: 'calipso',
    name: 'CALIPSO CLOUD LASER',
    noradId: '29108',
    category: 'other',
    altitudeM: 705_000,
    inclinationRad: (98.2 * Math.PI) / 180,
    omega0: 0.8,
    argLat0: 5.9,
    color: '#94A3B8',
    description: 'Lidar cloud profiling research satellite operated jointly by NASA and CNES.',
  },
  {
    id: 'cloudsat',
    name: 'CLOUDSAT METEOROLOGY',
    noradId: '29107',
    category: 'other',
    altitudeM: 705_000,
    inclinationRad: (98.2 * Math.PI) / 180,
    omega0: 0.8,
    argLat0: 6.0, 
    color: '#94A3B8',
    description: 'Radar climate observation satellite measuring cloud profiles and precipitation.',
  },
  {
    id: 'suomi-npp',
    name: 'SUOMI NPP (WEATHER/OBS)',
    noradId: '37849',
    category: 'other',
    altitudeM: 824_000,
    inclinationRad: (98.7 * Math.PI) / 180,
    omega0: 1.1,
    argLat0: 3.9,
    color: '#94A3B8',
    description: 'Meteorological satellite monitoring natural disasters, wildfire, and ozone layers.',
  },
];
