import { Concept } from './learningStore';

export const initialConcepts: Concept[] = [
  // --- Original 22 Concepts ---
  { id: '1', title: 'Quantum Entanglement', description: 'Particles sharing state regardless of distance.', mastery: 45, lastReviewed: new Date().toISOString(), tags: ['Physics', 'Quantum'] },
  { id: '2', title: 'Neural Synthetics', description: 'Artificial neural architectures mimicking biological cognition.', mastery: 12, lastReviewed: null, tags: ['AI', 'Cybernetics'] },
  { id: '3', title: 'Heuristic Saliency', description: 'Prioritizing data features based on weighted patterns.', mastery: 0, lastReviewed: null, tags: ['AI', 'Cognition'] },
  { id: '4', title: 'Schrödinger Paradox', description: 'Superposition problem applied to everyday objects.', mastery: 0, lastReviewed: null, tags: ['Quantum', 'Logic'] },
  { id: '5', title: 'Entropy Reversal', description: 'Decreasing disorder in closed systems.', mastery: 0, lastReviewed: null, tags: ['Physics', 'Theory'] },
  { id: '6', title: 'Zero-Knowledge Proofs', description: 'Proving knowledge without revealing the information.', mastery: 0, lastReviewed: null, tags: ['Crypto', 'Security'] },
  { id: '7', title: 'Kardashev Scale', description: 'Measuring civilization tech level by energy usage.', mastery: 0, lastReviewed: null, tags: ['Cosmology', 'Future'] },
  { id: '8', title: 'Neural Plasticity', description: 'Network reorganization and adaptation.', mastery: 0, lastReviewed: null, tags: ['Biology', 'AI'] },
  { id: '9', title: 'Blockchain Sharding', description: 'Partitioning networks to improve scalability.', mastery: 0, lastReviewed: null, tags: ['Web3', 'Architecture'] },
  { id: '10', title: 'Fermi Paradox', description: 'Contradiction between alien probability and lack of evidence.', mastery: 0, lastReviewed: null, tags: ['Space', 'Philosophy'] },
  { id: '11', title: 'Holographic Principle', description: '3D space encoded on a 2D boundary.', mastery: 0, lastReviewed: null, tags: ['Physics', 'Cosmology'] },
  { id: '12', title: 'Turing Completeness', description: 'Ability to simulate any Turing machine.', mastery: 0, lastReviewed: null, tags: ['Compute', 'Theory'] },
  { id: '13', title: 'Nanobot Swarm Tech', description: 'Autonomous molecular machines.', mastery: 0, lastReviewed: null, tags: ['Nano', 'Robotics'] },
  { id: '14', title: 'Dark Matter Synthesis', description: 'Creating non-baryonic matter.', mastery: 0, lastReviewed: null, tags: ['Physics', 'Advanced'] },
  { id: '15', title: 'Cognitive Load Theory', description: 'Working memory capacity limitations.', mastery: 0, lastReviewed: null, tags: ['Psychology', 'Education'] },
  { id: '16', title: 'Simulation Hypothesis', description: 'Existence as an artificial simulation.', mastery: 0, lastReviewed: null, tags: ['Philosophy', 'Theory'] },
  { id: '17', title: 'Edge Computing', description: 'Computation closer to data sources.', mastery: 0, lastReviewed: null, tags: ['Infrastructure', 'IoT'] },
  { id: '18', title: 'Homomorphic Crypto', description: 'Computing on encrypted data.', mastery: 0, lastReviewed: null, tags: ['Security', 'Math'] },
  { id: '19', title: 'Dyson Swarm Plans', description: 'Megastructures for stellar energy capture.', mastery: 0, lastReviewed: null, tags: ['Space', 'Energy'] },
  { id: '20', title: 'Semantic Satiation', description: 'Repetition causing temporary loss of meaning.', mastery: 0, lastReviewed: null, tags: ['Linguistics', 'Mind'] },
  { id: '21', title: 'Post-Humanism', description: 'Transforming human condition via tech.', mastery: 0, lastReviewed: null, tags: ['Philosophy', 'Future'] },
  { id: '22', title: 'Apophenia Diagnostics', description: 'Perceiving connections in unrelated data.', mastery: 0, lastReviewed: null, tags: ['Psychology', 'AI'] },

  // --- 100 Cybersecurity Concepts ---
  { id: '23', title: 'Ransomware', description: 'Malware that encrypts data and demands payment for the decryption key.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '24', title: 'Phishing', description: 'Fraudulent attempts to obtain sensitive information via deceptive emails.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Social Engineering'] },
  { id: '25', title: 'Zero-Day Exploit', description: 'An attack that targets a software vulnerability unknown to the vendor.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '26', title: 'DDoS Attack', description: 'Overwhelming a target system with a flood of internet traffic.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '27', title: 'Man-in-the-Middle (MITM)', description: 'Intercepting and potentially altering communications between two parties.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '28', title: 'SQL Injection (SQLi)', description: 'Inserting malicious SQL statements into entry fields for execution.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '29', title: 'Cross-Site Scripting (XSS)', description: 'Injecting malicious scripts into benign and trusted websites.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '30', title: 'Symmetric Encryption', description: 'Using the same cryptographic key for both encryption and decryption.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '31', title: 'Asymmetric Encryption', description: 'Using a public key for encryption and a private key for decryption.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '32', title: 'Hash Functions', description: 'Converting input data of any size into a fixed-size string of bytes.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '33', title: 'Zero Trust Architecture', description: 'Security model that requires strict identity verification for every person and device.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Architecture'] },
  { id: '34', title: 'Defense in Depth', description: 'Using multiple layers of security controls to protect information.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Architecture'] },
  { id: '35', title: 'Principle of Least Privilege (PoLP)', description: 'Giving a user only the access levels essential to perform their work.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'IAM'] },
  { id: '36', title: 'CIA Triad', description: 'The core goals of security: Confidentiality, Integrity, and Availability.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Fundamentals'] },
  { id: '37', title: 'Role-Based Access Control (RBAC)', description: 'Restricting network access based on the roles of individual users.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'IAM'] },
  { id: '38', title: 'Multi-Factor Authentication (MFA)', description: 'Requiring multiple methods of verification to confirm a user\'s identity.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'IAM'] },
  { id: '39', title: 'Firewall', description: 'Network security device that monitors and filters incoming and outgoing traffic.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '40', title: 'Intrusion Detection System (IDS)', description: 'System that monitors a network for malicious activity or policy violations.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '41', title: 'Virtual Private Network (VPN)', description: 'Extending a private network across a public network via encrypted tunnels.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '42', title: 'Web Application Firewall (WAF)', description: 'Filtering and monitoring HTTP traffic between a web application and the Internet.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '43', title: 'Buffer Overflow', description: 'Overwriting memory bounds to execute malicious code or crash a system.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '44', title: 'Path Traversal', description: 'Accessing files and directories stored outside the web root folder.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '45', title: 'Server-Side Request Forgery (SSRF)', description: 'Forcing a server to make requests to an unintended location.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '46', title: 'Insecure Deserialization', description: 'Manipulating serialized objects to achieve remote code execution.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '47', title: 'Security Information and Event Management (SIEM)', description: 'Real-time analysis of security alerts generated by hardware and applications.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'SecOps'] },
  { id: '48', title: 'Threat Hunting', description: 'Proactively searching through networks to detect and isolate advanced threats.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'SecOps'] },
  { id: '49', title: 'Cyber Kill Chain', description: 'A framework defining the stages of a cyberattack from reconnaissance to exfiltration.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'SecOps'] },
  { id: '50', title: 'MITRE ATT&CK', description: 'A globally-accessible knowledge base of adversary tactics and techniques.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'SecOps'] },
  { id: '51', title: 'Digital Forensics', description: 'The recovery and investigation of material found in digital devices.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Incident Response'] },
  { id: '52', title: 'Red Teaming', description: 'Simulating the actions of an adversary to test an organization\'s defenses.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Testing'] },
  { id: '53', title: 'Blue Teaming', description: 'Defending an organization against simulated or real cyber attacks.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Testing'] },
  { id: '54', title: 'Cloud Security Posture Management (CSPM)', description: 'Automating the identification and remediation of risks across cloud infrastructures.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cloud'] },
  { id: '55', title: 'Container Breakout', description: 'An attacker escaping a containerized environment to access the host system.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cloud'] },
  { id: '56', title: 'Static Application Security Testing (SAST)', description: 'Analyzing source code for security vulnerabilities without executing it.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '57', title: 'Dynamic Application Security Testing (DAST)', description: 'Analyzing a running application for vulnerabilities by interacting with it.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '58', title: 'Shift Left Security', description: 'Integrating security practices earlier in the software development lifecycle.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'DevSecOps'] },
  { id: '59', title: 'Threat Modeling', description: 'Identifying and prioritizing potential threats to a system during design.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Architecture'] },
  { id: '60', title: 'Bug Bounty', description: 'Programs offering rewards to individuals who find and report vulnerabilities.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Testing'] },
  { id: '61', title: 'Tailgating', description: 'Following an authorized person into a restricted area without consent.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Physical'] },
  { id: '62', title: 'Evil Twin', description: 'A fraudulent Wi-Fi access point that appears to be legitimate.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Wireless'] },
  { id: '63', title: 'Air Gapping', description: 'Physically isolating a computer or network from unsecured networks.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Physical'] },
  { id: '64', title: 'Faraday Cage', description: 'An enclosure used to block electromagnetic fields.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Physical'] },
  { id: '65', title: 'Cross-Site Request Forgery (CSRF)', description: 'Forcing an end user to execute unwanted actions on an authenticated web application.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '66', title: 'Spear Phishing', description: 'Targeted phishing attacks directed at specific individuals or companies.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Social Engineering'] },
  { id: '67', title: 'Whaling', description: 'A highly targeted phishing attack aimed at senior executives.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Social Engineering'] },
  { id: '68', title: 'Vishing', description: 'Voice phishing; using telephone calls to deceive users into giving up data.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Social Engineering'] },
  { id: '69', title: 'Public Key Infrastructure (PKI)', description: 'Policies and procedures to manage digital certificates and public-key encryption.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '70', title: 'Advanced Encryption Standard (AES)', description: 'A widely used symmetric encryption algorithm established by NIST.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '71', title: 'Steganography', description: 'The practice of concealing a file, message, image, or video within another file.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '72', title: 'Mandatory Access Control (MAC)', description: 'Access control where the OS constrains the ability of a subject to access an object.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'IAM'] },
  { id: '73', title: 'Single Sign-On (SSO)', description: 'Authentication scheme allowing a user to log in with a single ID and password to related systems.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'IAM'] },
  { id: '74', title: 'Demilitarized Zone (DMZ)', description: 'A physical or logical subnetwork exposing an organization\'s external-facing services.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '75', title: 'Honeypot', description: 'A decoy system designed to attract and monitor potential attackers.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '76', title: 'XML External Entity (XXE)', description: 'An attack against an application that parses XML input un-safely.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '77', title: 'Race Condition', description: 'A flaw occurring when the timing of events affects a system\'s correctness.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '78', title: 'Insecure Direct Object Reference (IDOR)', description: 'Accessing objects directly via user-supplied input without authorization checks.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '79', title: 'Security Orchestration, Automation, and Response (SOAR)', description: 'Technologies that enable organizations to collect security threats and respond automatically.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'SecOps'] },
  { id: '80', title: 'Incident Response Plan (IRP)', description: 'A set of instructions to help IT staff detect, respond to, and recover from network security incidents.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Incident Response'] },
  { id: '81', title: 'Disaster Recovery Plan (DRP)', description: 'A documented process to recover and protect IT infrastructure in the event of a disaster.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'SecOps'] },
  { id: '82', title: 'Business Continuity Plan (BCP)', description: 'A plan to ensure that business operations can continue during a crisis.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'SecOps'] },
  { id: '83', title: 'Cloud Access Security Broker (CASB)', description: 'Software that sits between cloud service users and applications to monitor activity.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cloud'] },
  { id: '84', title: 'Serverless Security', description: 'Securing applications where the server management is handled by the cloud provider.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cloud'] },
  { id: '85', title: 'Software Composition Analysis (SCA)', description: 'Identifying vulnerabilities and license restrictions in open-source components.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'DevSecOps'] },
  { id: '86', title: 'Interactive Application Security Testing (IAST)', description: 'Testing from within the application using instrumentation to detect flaws.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '87', title: 'OWASP Top 10', description: 'A standard awareness document representing a broad consensus about the most critical web app risks.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '88', title: 'Code Signing', description: 'The process of digitally signing executables to confirm the software author and guarantee integrity.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'AppSec'] },
  { id: '89', title: 'Penetration Testing', description: 'An authorized simulated cyberattack on a computer system to evaluate its security.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Testing'] },
  { id: '90', title: 'Piggybacking', description: 'An unauthorized person tagging along with an authorized person to gain entry, with their consent.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Physical'] },
  { id: '91', title: 'Rogue Access Point', description: 'An unauthorized wireless access point installed on a secure network.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Wireless'] },
  { id: '92', title: 'WPA3', description: 'The third generation of Wi-Fi Protected Access protocols for wireless security.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Wireless'] },
  { id: '93', title: 'RFID Cloning', description: 'Copying the data from an RFID tag to gain unauthorized access.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Physical'] },
  { id: '94', title: 'EMP (Electromagnetic Pulse)', description: 'A short burst of electromagnetic energy that can disrupt or damage electronic equipment.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Physical'] },
  { id: '95', title: 'Biometric Authentication', description: 'Using unique biological characteristics to verify an individual\'s identity.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'IAM'] },
  { id: '96', title: 'Wiper Malware', description: 'Malware designed to erase the hard drive of the computer it infects.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '97', title: 'Logic Bomb', description: 'Malicious code inserted into software that triggers when certain conditions are met.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '98', title: 'Rootkit', description: 'Software designed to enable access to a computer while masking its existence.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '99', title: 'Keylogger', description: 'Software or hardware that records the keys struck on a keyboard.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '100', title: 'Botnet', description: 'A network of private computers infected with malicious software and controlled as a group.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '101', title: 'Spyware', description: 'Software that aims to gather information about a person or organization without their knowledge.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '102', title: 'Adware', description: 'Software that automatically displays or downloads advertising material.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '103', title: 'Fileless Malware', description: 'Malicious software that uses legitimate programs to infect a computer without leaving a footprint.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Malware'] },
  { id: '104', title: 'Smishing', description: 'Phishing attacks executed via text message.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Social Engineering'] },
  { id: '105', title: 'Digital Signature', description: 'A mathematical scheme for verifying the authenticity of digital messages.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '106', title: 'Elliptic Curve Cryptography (ECC)', description: 'An approach to public-key cryptography based on the algebraic structure of elliptic curves.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '107', title: 'Quantum Cryptography', description: 'Using quantum mechanical properties to perform cryptographic tasks securely.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cryptography'] },
  { id: '108', title: 'Identity and Access Management (IAM)', description: 'Framework for managing electronic or digital identities.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'IAM'] },
  { id: '109', title: 'Discretionary Access Control (DAC)', description: 'Access control dictated by the owner of the object.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'IAM'] },
  { id: '110', title: 'Intrusion Prevention System (IPS)', description: 'System that monitors a network for malicious activity and takes action to block it.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '111', title: 'Subnetting', description: 'Dividing a network into two or more smaller networks for improved security and performance.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '112', title: 'Virtual Local Area Network (VLAN)', description: 'Any broadcast domain that is partitioned and isolated in a computer network.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '113', title: 'Network Access Control (NAC)', description: 'Unifying endpoint security technology, user or system authentication, and network security enforcement.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Network'] },
  { id: '114', title: 'Security Misconfiguration', description: 'Failing to implement all security controls for a server or web application.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '115', title: 'Broken Authentication', description: 'Vulnerabilities that allow attackers to compromise passwords or session tokens.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Vulnerability'] },
  { id: '116', title: 'Cloud Workload Protection Platform (CWPP)', description: 'A security solution focused on protecting server workloads in hybrid and multi-cloud environments.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cloud'] },
  { id: '117', title: 'Kubernetes RBAC', description: 'Role-based access control specific to managing permissions within a Kubernetes cluster.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cloud'] },
  { id: '118', title: 'VPC Peering', description: 'A networking connection between two VPCs that enables traffic routing between them.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cloud'] },
  { id: '119', title: 'S3 Bucket Policies', description: 'JSON-based access policy language for managing permissions to Amazon S3 resources.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Cloud'] },
  { id: '120', title: 'Secret Management', description: 'Tools and processes used to securely store and manage digital authentication credentials.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'DevSecOps'] },
  { id: '121', title: 'Data Loss Prevention (DLP)', description: 'Strategy for ensuring that sensitive data is not lost, misused, or accessed by unauthorized users.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'Data'] },
  { id: '122', title: 'Endpoint Detection and Response (EDR)', description: 'Endpoint security solutions that continuously monitor end-user devices to detect threats.', mastery: 0, lastReviewed: null, tags: ['Cybersecurity', 'SecOps'] },

  // --- 100 Performance Concepts ---
  { id: '123', title: 'Largest Contentful Paint (LCP)', description: 'A Core Web Vital metric measuring the time it takes for the largest image or text block to render.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Web'] },
  { id: '124', title: 'First Input Delay (FID)', description: 'A metric measuring the time from a user\'s first interaction to the browser\'s response.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Web'] },
  { id: '125', title: 'Cumulative Layout Shift (CLS)', description: 'A metric measuring the visual stability of a page during load.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Web'] },
  { id: '126', title: 'Time to First Byte (TTFB)', description: 'The time taken for a browser to receive the first byte of page content.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '127', title: 'Time to Interactive (TTI)', description: 'The time it takes for a page to become fully interactive.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Web'] },
  { id: '128', title: 'First Paint (FP)', description: 'The time when the browser renders the first pixel to the screen.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Web'] },
  { id: '129', title: 'First Contentful Paint (FCP)', description: 'The time when the browser renders the first piece of DOM content.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Web'] },
  { id: '130', title: 'Speed Index', description: 'A metric showing how quickly the contents of a page are visibly populated.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Web'] },
  { id: '131', title: 'Total Blocking Time (TBT)', description: 'The total time a page is blocked from responding to user input during load.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Web'] },
  { id: '132', title: 'Browser Caching', description: 'Storing webpage resources locally to speed up subsequent visits.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '133', title: 'Content Delivery Network (CDN)', description: 'A distributed network of servers delivering web content based on user location.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '134', title: 'Redis', description: 'An in-memory data structure store used as a database, cache, and message broker.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '135', title: 'Memcached', description: 'A general-purpose distributed memory-caching system.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '136', title: 'Cache Invalidation', description: 'The process of removing or updating cached data when the source data changes.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '137', title: 'Least Recently Used (LRU)', description: 'A cache eviction algorithm that discards the least recently used items first.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '138', title: 'Least Frequently Used (LFU)', description: 'A cache eviction algorithm that discards the least frequently accessed items first.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '139', title: 'Cache Stampede', description: 'A surge in database load when a highly requested cache entry expires.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '140', title: 'Edge Caching', description: 'Storing data at the edge of the network, closer to the end-user.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Caching'] },
  { id: '141', title: 'Service Workers', description: 'Scripts that run in the background, enabling features like offline caching.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '142', title: 'Code Splitting', description: 'Breaking down a large bundle into smaller chunks loaded on demand.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '143', title: 'Lazy Loading', description: 'Deferring the loading of non-critical resources until they are needed.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '144', title: 'Tree Shaking', description: 'Dead code elimination in JavaScript bundles.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '145', title: 'Minification', description: 'Removing unnecessary characters from code without changing its functionality.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '146', title: 'Image Optimization', description: 'Reducing image file size without unacceptably degrading quality.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '147', title: 'WebP', description: 'A modern image format that provides superior lossless and lossy compression.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '148', title: 'Font Loading Optimization', description: 'Strategies to load web fonts quickly without blocking text rendering.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '149', title: 'Critical CSS', description: 'Extracting and inlining the CSS required to render above-the-fold content.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '150', title: 'Virtual DOM', description: 'A lightweight JavaScript representation of the DOM used to optimize updates.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '151', title: 'Connection Pooling', description: 'Maintaining a pool of active database connections to reuse for subsequent requests.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Backend'] },
  { id: '152', title: 'Query Optimization', description: 'Improving database query execution time through various techniques.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Backend'] },
  { id: '153', title: 'Database Indexing', description: 'Creating data structures to speed up data retrieval operations.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '154', title: 'Denormalization', description: 'Adding redundant data to a database to improve read performance.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '155', title: 'Read Replicas', description: 'Copies of a primary database used to handle read-heavy workloads.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '156', title: 'Sharding', description: 'Partitioning a large database horizontally across multiple servers.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '157', title: 'N+1 Problem', description: 'An anti-pattern where an application makes N additional database queries to fetch related data.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Backend'] },
  { id: '158', title: 'Eager Loading', description: 'Fetching related records alongside the initial query to avoid N+1 problems.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Backend'] },
  { id: '159', title: 'Pagination', description: 'Dividing a large dataset into smaller, manageable chunks for display.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Backend'] },
  { id: '160', title: 'Rate Limiting', description: 'Controlling the number of requests a user can make to an API within a timeframe.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '161', title: 'HTTP/2', description: 'A major revision of the HTTP protocol focusing on performance via multiplexing.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '162', title: 'HTTP/3', description: 'The next generation HTTP protocol using QUIC to reduce latency.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '163', title: 'QUIC', description: 'A UDP-based transport protocol designed for lower latency than TCP.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '164', title: 'TCP Slow Start', description: 'An algorithm used by TCP to control the flow of data to avoid network congestion.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '165', title: 'TLS Handshake', description: 'The process of establishing a secure connection; optimizing it reduces latency.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '166', title: 'DNS Resolution', description: 'Translating domain names into IP addresses; caching this speeds up loads.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '167', title: 'Keep-Alive', description: 'Maintaining open connections to avoid the overhead of establishing new ones.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '168', title: 'Gzip/Brotli Compression', description: 'Compressing text-based responses (HTML, CSS, JS) to reduce transfer size.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '169', title: 'WebSockets', description: 'A protocol for full-duplex communication channels over a single TCP connection.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '170', title: 'Server-Sent Events (SSE)', description: 'A standard allowing a browser to receive automatic updates from a server.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Network'] },
  { id: '171', title: 'Multithreading', description: 'Executing multiple threads concurrently to utilize multiple CPU cores.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '172', title: 'Concurrency', description: 'Handling multiple tasks simultaneously, often via interleaving.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '173', title: 'Async/Await', description: 'A programming paradigm for handling asynchronous operations cleanly.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '174', title: 'Event Loop', description: 'The mechanism that handles asynchronous callbacks in environments like Node.js.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '175', title: 'Context Switching', description: 'The overhead of a CPU switching from one process or thread to another.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '176', title: 'CPU Bound vs I/O Bound', description: 'Understanding if a process is limited by processor speed or input/output speed.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '177', title: 'Memory Leaks', description: 'When a program fails to release discarded memory, leading to performance degradation.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '178', title: 'Garbage Collection (GC)', description: 'Automatic memory management; optimizing GC pauses improves performance.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '179', title: 'Thread Pool', description: 'A collection of pre-instantiated, reusable threads to handle tasks efficiently.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '180', title: 'Deadlocks', description: 'When two or more threads are blocked forever, waiting for each other.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '181', title: 'Horizontal Scaling', description: 'Adding more machines to a system to handle increased load.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Scalability'] },
  { id: '182', title: 'Vertical Scaling', description: 'Adding more power (CPU, RAM) to an existing machine to handle load.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Scalability'] },
  { id: '183', title: 'Load Balancing', description: 'Distributing incoming network traffic across multiple servers.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Scalability'] },
  { id: '184', title: 'Microservices Architecture', description: 'Structuring an application as a collection of loosely coupled services.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '185', title: 'Serverless Computing', description: 'Executing code without managing servers, scaling automatically per request.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Scalability'] },
  { id: '186', title: 'Auto-scaling', description: 'Automatically adjusting compute resources based on current demand.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Scalability'] },
  { id: '187', title: 'Stateful vs Stateless', description: 'Designing services to be stateless improves scalability and load balancing.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '188', title: 'Message Queues', description: 'Asynchronous service-to-service communication used to decouple heavy processing.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '189', title: 'Apache Kafka', description: 'A distributed event streaming platform used for high-performance data pipelines.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '190', title: 'RabbitMQ', description: 'An open-source message-broker software used to decouple workloads.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '191', title: 'ACID Properties', description: 'Atomicity, Consistency, Isolation, Durability; guarantees for database transactions.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '192', title: 'CAP Theorem', description: 'Distributed databases can only provide two of: Consistency, Availability, Partition Tolerance.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '193', title: 'Eventual Consistency', description: 'A consistency model where given no new updates, all nodes eventually return the same value.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '194', title: 'B-Trees', description: 'Self-balancing tree data structures widely used in databases for indexing.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '195', title: 'Write-Ahead Logging (WAL)', description: 'A database technique to ensure atomicity and durability by logging changes before applying them.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '196', title: 'Bloom Filters', description: 'Space-efficient probabilistic data structures to test whether an element is in a set.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '197', title: 'Materialized Views', description: 'Database objects containing the results of a query, updated periodically to speed up reads.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '198', title: 'Flame Graphs', description: 'Visualizations of profiled software to identify performance bottlenecks quickly.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Profiling'] },
  { id: '199', title: 'Application Performance Monitoring (APM)', description: 'Tools used to monitor software performance and trace transactions.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Profiling'] },
  { id: '200', title: 'Distributed Tracing', description: 'A method to monitor applications built on a microservices architecture.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Profiling'] },
  { id: '201', title: 'Latency Percentiles (p95, p99)', description: 'Metrics indicating the latency experienced by the worst 5% or 1% of requests.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Profiling'] },
  { id: '202', title: 'CQRS', description: 'Command Query Responsibility Segregation; separating read and update operations.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '203', title: 'Event Sourcing', description: 'Storing the state of a system as a sequence of state-changing events.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '204', title: 'Circuit Breaker Pattern', description: 'Preventing an application from repeatedly trying to execute an operation likely to fail.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '205', title: 'Bulkhead Pattern', description: 'Isolating elements of an application into pools to prevent cascading failures.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '206', title: 'Debouncing', description: 'Ensuring a function is not called too frequently by delaying its execution.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '207', title: 'Throttling', description: 'Limiting the execution of a function to a maximum of once every X milliseconds.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '208', title: 'Memoization', description: 'Caching the results of expensive function calls based on their inputs.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '209', title: 'Object Pooling', description: 'Reusing objects from a pool instead of instantiating and destroying them continuously.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Compute'] },
  { id: '210', title: 'Flyweight Pattern', description: 'Minimizing memory usage by sharing as much data as possible with similar objects.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '211', title: 'Proxy Pattern', description: 'Using a surrogate object to control access, often used for lazy loading or caching.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '212', title: 'Bundle Phobia', description: 'The concern regarding the size of npm packages added to a frontend bundle.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] },
  { id: '213', title: 'Throughput', description: 'The number of requests a system can handle per unit of time.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Profiling'] },
  { id: '214', title: 'Saturation', description: 'The degree to which a resource has extra work queued up that it cannot process.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Profiling'] },
  { id: '215', title: 'Prometheus & Grafana', description: 'Industry-standard open-source tools for metrics collection and visualization.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Profiling'] },
  { id: '216', title: 'Dead Tuple', description: 'An old version of a row in MVCC databases (like PostgreSQL) that needs to be vacuumed.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '217', title: 'NoSQL vs SQL', description: 'Choosing between relational and non-relational databases based on read/write patterns.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '218', title: 'Connection Limits', description: 'The maximum number of concurrent database connections; exceeding causes queueing.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Database'] },
  { id: '219', title: 'Bottleneck Analysis', description: 'The process of identifying the single slowest component in a system.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Profiling'] },
  { id: '220', title: 'Data Locality', description: 'Processing data close to where it resides to minimize network transfer times.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '221', title: 'Backpressure', description: 'Signaling from a slow consumer to a fast producer to slow down data emission.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Architecture'] },
  { id: '222', title: 'Pre-fetching', description: 'Loading resources or data before they are strictly needed by the user.', mastery: 0, lastReviewed: null, tags: ['Performance', 'Frontend'] }
];
