import { Hexagon } from "lucide-react";
import type {
    WorldPlugin,
    GeoEntity,
    TimeRange,
    PluginContext,
    LayerConfig,
    CesiumEntityOptions,
} from "@/core/plugins/PluginTypes";
import { pluginManager } from "@/core/plugins/PluginManager";
import { generateHexagonDensityFeed } from "@/core/hexagons/hexagonFeeds";

export class EntityDensityPlugin implements WorldPlugin {
    readonly id = "entity-density";
    readonly name = "Global Density Map";
    readonly description = "Aggregates all entities into a 3D hexagon density layer";
    readonly icon = Hexagon;
    readonly category = "infrastructure" as const;
    readonly version = "1.0.0";

    private context: PluginContext | null = null;

    async initialize(ctx: PluginContext): Promise<void> {
        this.context = ctx;
    }

    destroy(): void {
        this.context = null;
    }

    async fetch(_timeRange: TimeRange): Promise<GeoEntity[]> {
        // Collect entities from all other active plugins except this one
        const allEntities = pluginManager.getAllEntities().filter(e => e.pluginId !== this.id);
        
        // Generate hexagon density feed
        const hexFeed = generateHexagonDensityFeed(allEntities, 10); // 10 degree cell size

        return hexFeed.map(h => ({
            ...h.entity,
            pluginId: this.id, // Ensure we tag it as from this plugin
            properties: {
                ...h.entity.properties,
                cesiumOptions: h.options // Store the generated options
            }
        }));
    }

    getPollingInterval(): number {
        return 5000; // Update hexagons every 5 seconds
    }

    getLayerConfig(): LayerConfig {
        return {
            color: "#FFFFFF",
            clusterEnabled: false,
            clusterDistance: 0,
        };
    }

    renderEntity(entity: GeoEntity): CesiumEntityOptions {
        // Return the options generated by hexagonFeeds
        return (entity.properties.cesiumOptions as CesiumEntityOptions) || {
            type: "hexagon",
            color: "#ea4335",
            size: 10,
        };
    }
}
