const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const docsPath = path.join(root, 'DOCS.md');
const packagePath = path.join(root, 'package.json');
const startMarker = '<!-- GENERATED:START -->';
const endMarker = '<!-- GENERATED:END -->';

function readDirectories(relativePath) {
  const absolutePath = path.join(root, relativePath);
  return fs
    .readdirSync(absolutePath, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.'))
    .map((entry) => entry.name)
    .sort();
}

function buildGeneratedSection() {
  const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
  const sourceDirectories = readDirectories('src');
  const documentationDirectories = readDirectories('docs');
  const verificationScripts = Object.keys(packageJson.scripts)
    .filter((name) => name === 'test' || name === 'typecheck' || name === 'build' || name.startsWith('qa:') || name.startsWith('ui:') || name.startsWith('perf:'))
    .sort();

  return [
    startMarker,
    '## Generated Project Inventory',
    '',
    'This section is generated by `npm run docs:generate`. Do not edit it manually; use `npm run docs:check` to verify it is current.',
    '',
    '### Source Roots',
    '',
    ...sourceDirectories.map((directory) => `- \`src/${directory}/\``),
    '',
    '### Documentation Roots',
    '',
    ...documentationDirectories.map((directory) => `- \`docs/${directory}/\``),
    '',
    '### Verification Commands',
    '',
    ...verificationScripts.map((script) => `- \`npm run ${script}\``),
    '',
    endMarker
  ].join('\n');
}

function updateDocumentation(content, generatedSection) {
  const startIndex = content.indexOf(startMarker);
  const endIndex = content.indexOf(endMarker);

  if (startIndex === -1 && endIndex === -1) {
    return `${content.trimEnd()}\n\n${generatedSection}\n`;
  }

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error('DOCS.md has incomplete generated-section markers. Restore both markers before generating documentation.');
  }

  return `${content.slice(0, startIndex)}${generatedSection}${content.slice(endIndex + endMarker.length)}`;
}

const checkOnly = process.argv.includes('--check');
const currentDocumentation = fs.readFileSync(docsPath, 'utf8');
const nextDocumentation = updateDocumentation(currentDocumentation, buildGeneratedSection());

if (checkOnly) {
  if (currentDocumentation !== nextDocumentation) {
    console.error('DOCS.md is out of date. Run: npm run docs:generate');
    process.exitCode = 1;
  } else {
    console.log('DOCS.md generated inventory is current.');
  }
} else {
  fs.writeFileSync(docsPath, nextDocumentation);
  console.log('DOCS.md generated inventory updated.');
}